name: 'CI'
on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.event_name  == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Test JUnit test import
        uses: ./
        with:
          check_name: Example JUnit Test Report
          report_paths: '**/surefire-reports/TEST-*.xml'
          include_passed: true
          detailed_summary: true
          summary: '<table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> test </td></tr></tbody></table>'
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}